%YAML:1.0
---
path:
  device: "/dev/v4l/by-path/pci-0000:06:00.3-usb-0:1.3:1.0-video-index0"
  left_imgs_directory: "../data/image/chessboard_10_7_paper_st_1280_800/"
  right_imgs_directory: "../data/image/chessboard_10_7_paper_st_1280_800/"
  img_left_filename: "left"
  img_right_filename: "right"
  extension: "png"
  filename_left_cam_params: "cam_left.yml"
  filename_right_cam_params: "cam_right.yml"
  filename_stereo_cam_params: "cam_stereo.yml"
  out_params: "../result/"
  num_test_img: 1

camera:
  video_id: 0
  size_im: [1280, 800]
  api_preference: 200 #cv::CAP_V4L2
  use_mjpg: true

roi:
  x: 0
  y: 0
  width: 500
  height: 500

vizualizer:
  win_name: "LeftFlow"
  size_frame_vis: [1280,800]

chessboard:
  board_width: 9
  board_height: 6
  square_size: 0.02423

stereo_sgbm:
  min_disp: 0
  max_disp: 144
  block_size: 5
  uniqueness_ratio: 10
  speckle_ws: 100
  speckle_range: 32
  use_wls: true
  wls_lambda: 80000
  wls_sigma: 1.5
  median_blur_size: 0

velocity_tracker:
  max_corners: 400
  quality_level: 0.01
  min_distance: 10.0
  min_pnp_points: 12
  min_inliers: 15
  inlier_ratio_threshold: 0.2
  ransac_reproj_error: 3.0
  ransac_iter: 200
  ransac_conf: 0.99
  min_depth: 0.5
  max_depth: 20.0
  smoothed_alpha: 0.8